DROP DATABASE IF EXISTS CalculatorDB;
CREATE DATABASE IF NOT EXISTS CalculatorDB;

USE CalculatorDB;

CREATE TABLE User (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(100) NOT NULL
);

CREATE TABLE UserSession (
    UserID INT NOT NULL,
    SessionID VARCHAR(100) NOT NULL PRIMARY KEY,
    Created_at DATETIME,
    FOREIGN KEY (UserID) REFERENCES User (ID)
);
